# Generated by Django 5.1.6 on 2025-03-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gemini2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('explain', models.TextField()),
                ('aiexplain', models.TextField()),
                ('filename', models.CharField(max_length=35)),
                ('file', models.FileField(upload_to='gemini/')),
                ('today', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Gemini',
        ),
    ]
